# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsgroup',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.Time'),
        ),
    ]
