# Generated by Django 2.1.7 on 2019-03-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_auto_20190321_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.Carrier')),
            ],
        ),
    ]
